# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Basic build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # manual

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: ReadWriteCookie/ReadWriteCookie.sln

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build --no-restore  ${{ env.SOLUTION_PATH }}
    - name: Test
      run: dotnet test --no-build --verbosity normal  ${{ env.SOLUTION_PATH }}
